/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ah7gY46wBZg
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { ScrollArea } from "@/components/ui/scroll-area"

export function Editor() {
  return (
    <div className="p-6">
      <div className="grid gap-6">
        <h2 className="font-semibold text-xl">Text Editor</h2>
        <div className="flex justify-between items-center">
          <div className="w-3/4">
            <Card className="h-auto">
              <CardHeader className="p-4 bg-[#f2f2f2]">
                <h3 className="font-semibold text-lg">Document</h3>
              </CardHeader>
              <CardContent className="p-4 text-sm">
                <p className="mb-4">
                  Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                  throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
                </p>
                <p className="mb-4">
                  The king thought long and hard, and finally came up with a brilliant plan : he would tax the jokes in
                  the kingdom.
                </p>
              </CardContent>
            </Card>
          </div>
          <div className="w-1/4">
            <h3 className="font-semibold text-lg mb-4">Comments</h3>
            <ScrollArea className="h-72 w-full rounded-md border">
              <div className="p-4 text-sm">
                <div className="flex items-start gap-4 mb-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage alt="@user1" src="/placeholder-user.jpg" />
                    <AvatarFallback>U1</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1.5">
                    <div className="flex items-center gap-2">
                      <div className="font-semibold">@user1</div>
                      <div className="text-gray-500 text-xs dark:text-gray-400">5 mins ago</div>
                    </div>
                    <div>I think the king's plan is quite innovative.</div>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage alt="@user2" src="/placeholder-user.jpg" />
                    <AvatarFallback>U2</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1.5">
                    <div className="flex items-center gap-2">
                      <div className="font-semibold">@user2</div>
                      <div className="text-gray-500 text-xs dark:text-gray-400">2 mins ago</div>
                    </div>
                    <div>Yes, but it could lead to a decrease in humor in the kingdom.</div>
                  </div>
                </div>
              </div>
            </ScrollArea>
          </div>
        </div>
      </div>
    </div>
  )
}
